#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { abs, asArray, collectDocuments, readJson } from "./lib/core.mjs";

const configPath = ".agents/knowledge.config.json";
const manifestPath = ".agents/knowledge-core/manifest.json";
const checkOnly = process.argv.includes("--check");

function buildGraph(config, manifest, docs) {
  const nodes = [];
  const edges = [];

  for (const doc of docs) {
    const fm = doc.frontmatter;
    const node = {
      id: fm.id,
      type: fm.type,
      status: fm.status,
      owner: fm.owner,
      summary: fm.summary,
      path: doc.file,
      canonical_for: asArray(fm.canonical_for),
      last_reviewed: fm.last_reviewed
    };

    for (const key of ["depends_on", "related", "code_refs", "verified_by", "supersedes", "source_refs", "tags"]) {
      if (fm[key] !== undefined) node[key] = fm[key];
    }
    if (fm.superseded_by !== undefined) node.superseded_by = fm.superseded_by;

    nodes.push(node);

    for (const target of asArray(fm.canonical_for).filter((topic) => topic !== fm.id)) {
      edges.push({ from: fm.id, to: target, type: "canonical_for" });
    }
    for (const target of asArray(fm.depends_on)) {
      edges.push({ from: fm.id, to: target, type: "depends_on" });
    }
    for (const target of asArray(fm.related)) {
      edges.push({ from: fm.id, to: target, type: "related" });
    }
    for (const target of asArray(fm.supersedes)) {
      edges.push({ from: fm.id, to: target, type: "supersedes" });
    }
    if (fm.superseded_by) {
      edges.push({ from: fm.id, to: fm.superseded_by, type: "superseded_by" });
    }
    for (const target of asArray(fm.code_refs)) {
      edges.push({ from: fm.id, to: target, type: "code_ref" });
    }
  }

  edges.sort((a, b) => `${a.from}:${a.type}:${a.to}`.localeCompare(`${b.from}:${b.type}:${b.to}`));

  return {
    schemaVersion: config.schemaVersion,
    core: {
      name: manifest.name,
      version: manifest.version
    },
    generated: true,
    source: config.paths.docsRoot,
    nodes,
    edges
  };
}

function buildKnowledgeMap(config, docs) {
  const lines = [
    "# Knowledge Map",
    "",
    "> Generated by `.agents/knowledge-core/scripts/build-index.mjs`. Do not edit manually.",
    "",
    "## Documents",
    ""
  ];

  if (docs.length === 0) {
    lines.push("_No authored knowledge documents found._", "");
    return lines.join("\n");
  }

  const byType = new Map();
  for (const doc of docs) {
    const type = doc.frontmatter.type || "unknown";
    if (!byType.has(type)) byType.set(type, []);
    byType.get(type).push(doc);
  }

  for (const [type, group] of [...byType.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`### ${type}`, "");
    for (const doc of group) {
      const fm = doc.frontmatter;
      lines.push(`- [${fm.id}](${relativeFromGenerated(config, doc.file)}) - ${fm.summary}`);
      lines.push(`  - status: \`${fm.status}\`; owner: \`${fm.owner}\`; canonical_for: ${asArray(fm.canonical_for).map((topic) => `\`${topic}\``).join(", ")}`);
    }
    lines.push("");
  }

  lines.push("## Generated Outputs", "");
  lines.push(`- \`${config.generated.llmsTxt}\``);
  lines.push(`- \`${config.generated.knowledgeMap}\``);
  lines.push(`- \`${config.generated.knowledgeGraph}\``);
  lines.push("");

  return lines.join("\n");
}

function relativeFromGenerated(config, file) {
  return path.posix.relative(config.paths.generatedRoot, file);
}

function buildLlmsTxt(config, manifest, docs) {
  const agentEntrypoints = unique([
    config.entrypoints.agentInstructions,
    manifest.entrypoints?.claudeInstructions,
    manifest.entrypoints?.agentLayerReadme
  ]);
  const projectKnowledge = unique([
    config.entrypoints.humanKnowledgeHome,
    config.generated.knowledgeMap
  ]);
  const coreSpecification = unique([
    manifest.canonicalPaths?.core ? path.posix.join(manifest.canonicalPaths.core, "README.md") : null,
    manifest.canonicalPaths?.config,
    manifest.canonicalPaths?.schema,
    manifest.canonicalPaths?.lifecycle,
    manifest.canonicalPaths?.routing,
    manifest.canonicalPaths?.memoryTaxonomy,
    manifest.canonicalPaths?.agentMemoryPolicy,
    manifest.canonicalPaths?.skillsSpec
  ]);
  const generatedOutputs = unique(Object.values(config.generated || {}).filter((file) => file !== config.generated.llmsTxt));

  const lines = [
    "# llms.txt",
    "",
    "> Generated by `.agents/knowledge-core/scripts/build-index.mjs`. Do not store agent behavior rules here.",
    "",
    "Agent instructions:"
  ];

  for (const file of agentEntrypoints) lines.push(`- \`${file}\``);

  lines.push(
    "",
    "Project knowledge:"
  );

  for (const file of projectKnowledge) lines.push(`- \`${file}\``);

  lines.push(
    "",
    "Core specification:"
  );

  for (const file of coreSpecification) lines.push(`- \`${file}\``);

  lines.push(
    "",
    "Authored documents:",
    ""
  );

  for (const doc of docs) {
    const fm = doc.frontmatter;
    lines.push(`- \`${doc.file}\` - ${fm.id}: ${fm.summary}`);
  }

  if (docs.length === 0) lines.push("- _No authored knowledge documents found._");

  lines.push("");
  lines.push("Generated outputs:");
  for (const file of generatedOutputs) lines.push(`- \`${file}\``);
  lines.push("");

  return lines.join("\n");
}

function unique(values) {
  return [...new Set(values.filter(Boolean))];
}

function writeOrCheck(file, content) {
  const current = fs.existsSync(abs(file)) ? fs.readFileSync(abs(file), "utf8") : null;
  if (current === content) return false;

  if (checkOnly) {
    console.error(`Generated file is stale: ${file}`);
    process.exitCode = 1;
    return true;
  }

  fs.mkdirSync(path.dirname(abs(file)), { recursive: true });
  fs.writeFileSync(abs(file), content);
  return true;
}

function main() {
  const config = readJson(configPath);
  const manifest = readJson(manifestPath);
  const docs = collectDocuments(config);
  const graph = buildGraph(config, manifest, docs);

  const outputs = [
    [config.generated.llmsTxt, buildLlmsTxt(config, manifest, docs)],
    [config.generated.knowledgeMap, buildKnowledgeMap(config, docs)],
    [config.generated.knowledgeGraph, `${JSON.stringify(graph, null, 2)}\n`]
  ];

  let changed = 0;
  for (const [file, content] of outputs) {
    if (writeOrCheck(file, content)) changed += 1;
  }

  if (checkOnly) {
    if (process.exitCode) {
      console.error("Knowledge indexes are stale.");
      process.exit(process.exitCode);
    }
    console.log("Knowledge indexes are current.");
    return;
  }

  console.log(`Knowledge indexes built: ${docs.length} document(s), ${changed} file(s) updated.`);
}

main();
